--- #handlers concept
- hosts: webservers
  become: yes

  tasks: 
    - name: install httpd on webservers
      action: yum name=httpd state=installed
      notify: start service httpd


  handlers:
     - name: start service httpd
       action: service name=httpd state=started   
